# Circuit Breaker Configuration Template
# Add these properties to your service's application.yml

# Feign Configuration with Circuit Breaker
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      # Example for specific service
      account-service:
        connectTimeout: 3000
        readTimeout: 8000
        loggerLevel: full

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      feign:
        registerHealthIndicator: true
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 60
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 5
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 8s
        eventConsumerBufferSize: 10
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 5s
        eventConsumerBufferSize: 10
  timelimiter:
    instances:
      feign:
        timeoutDuration: 15s
      default:
        timeoutDuration: 10s

# Actuator endpoints for monitoring circuit breaker
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true


